'''<summary>Correponde a las constantes de nombres de objetos de la base de datos del Sistema.
''' </summary>
Public Class Tablas
    '''<summary>Tabla de datos de antecedentes personales</summary>
    Public Const RH_PER_EMPLEADO As String = "RH_PER_EMPLEADO"
    '''<summary>Tabla de antecedentes laborales</summary>
    Public Const RH_PER_ANTECEDENTE_LABORAL As String = "RH_PER_ANTECEDENTE_LABORAL"
    '''<summary>Tabla de antecedentes previsionales</summary>
    Public Const RH_PER_ANTECEDENTE_PREVIS As String = "RH_PER_ANTECEDENTE_PREVIS"
    '''<summary>Tabla de antecedentes de datos previsionales de ahorro voluntario</summary>
    Public Const RH_PER_ANTECEDENTE_APV As String = "RH_PER_ANTECEDENTE_APV"
    '''<summary>Tabla de antecedentes curriculares (estudios)</summary>
    Public Const RH_PER_ANTECEDENTE_CURRI As String = "RH_PER_ANTECEDENTE_CURRI"
    '''<summary>Tabla de antecedentes de datos relativos a remuneración</summary>
    Public Const RH_PER_ANTECEDENTE_REMUN As String = "RH_PER_ANTECEDENTE_REMUN"
    Public Const RH_PER_EVENTO_ADMIN As String = "RH_PER_EVENTO_ADMIN"
    Public Const RH_PER_EVENTO_ADMIN_DET As String = "RH_PER_EVENTO_ADMIN_DET"
    Public Const RH_PER_HORAS_EXTRAS_APROBADAS As String = " RH_PER_HORAS_EXTRAS_APROBADAS"
    Public Const RH_PER_EVENTO_ADMIN_SALDO As String = "RH_PER_EVENTO_ADMIN_SALDO"
    Public Const RH_PER_ANTECEDENTE_ACADEM As String = "RH_PER_ANTECEDENTE_ACADEM"
    Public Const RH_PER_NIVEL_ESTUDIO As String = "RH_PER_NIVEL_ESTUDIO"
    Public Const RH_PER_REGIMEN_ESTUDIO As String = "RH_PER_REGIMEN_ESTUDIO"
    Public Const RH_PER_PROFESION_OFICIO As String = "RH_PER_PROFESION_OFICIO"
    Public Const RH_PER_TIPO_NIVEL_ESTUDIO As String = "RH_PER_TIPO_NIVEL_ESTUDIO"
    Public Const GEN_PAIS As String = "GEN_PAIS"
    Public Const GEN_REGION As String = "GEN_REGION"
    Public Const GEN_CIUDAD As String = "GEN_CIUDAD"
    Public Const GEN_COMUNA As String = "GEN_COMUNA"
    Public Const GEN_ORGANIZACION As String = "GEN_ORGANIZACION"
    Public Const RH_REM_AFP As String = "RH_REM_AFP"
    Public Const RH_REM_AFP_DETALLE As String = "RH_REM_AFP_DETALLE"
    Public Const RH_REM_ISAPRE As String = "RH_REM_ISAPRE"
    Public Const RH_REM_APV As String = "RH_REM_APV"
    Public Const GEN_IPC As String = "GEN_IPC"
    Public Const RH_PER_TIPO_UNIDAD As String = "RH_PER_TIPO_UNIDAD"
    Public Const RH_REM_CALIDAD_JURIDICA As String = "RH_REM_CALIDAD_JURIDICA"
    Public Const RH_PER_ESTAMENTO As String = "RH_PER_ESTAMENTO"
    Public Const RH_PER_DIRECCION As String = "RH_PER_DIRECCION"
    Public Const RH_PER_DEPARTAMENTO As String = "RH_PER_DEPARTAMENTO"
    Public Const RH_PER_SUB_DEPARTAMENTO As String = "RH_PER_SUB_DEPARTAMENTO"
    Public Const RH_REM_CENTRO_COSTO_CONTABLE As String = "RH_REM_CENTRO_COSTO_CONTABLE"
    Public Const RH_REM_CENTRO_COSTO_PRESUPUESTO As String = "RH_REM_CENTRO_COSTO_PRESUPUESTO"
    Public Const RH_PER_MOTIVO_RETIRO As String = "RH_PER_MOTIVO_RETIRO"
    Public Const RH_PER_BANCO As String = "RH_PER_BANCO"
    Public Const RH_PER_TIPO_CUENTA_BANCO As String = "RH_PER_TIPO_CUENTA_BANCO"
    Public Const RH_REM_TRAMO_ASIGNACION_FAMILIAR As String = "RH_REM_TRAMO_ASIGNACION_FAMILIAR"
    Public Const RH_PER_ASOCIACION_GREMIAL As String = "RH_PER_ASOCIACION_GREMIAL"
    Public Const RH_PER_LICENCIA_MEDICA As String = "RH_PER_LICENCIA_MEDICA"
    Public Const RH_PER_TIPO_LICENCIA_MEDICA As String = "RH_PER_TIPO_LICENCIA_MEDICA"
    Public Const RH_PER_CAUSA_RECHAZO_LICENCIA_MEDICA As String = "RH_PER_CAUSA_RECHAZO_LICENCIA_MEDICA"
    Public Const SELECT_RH_REM_PERIODO As String = "SELECT_RH_REM_PERIODO"
    Public Const RH_REM_PERIODO As String = "RH_REM_PERIODO"
    Public Const RH_REM_ITEM_RELIQUIDADO As String = "RH_REM_ITEM_RELIQUIDADO"
    Public Const RH_PER_HORAS_EXTRAS As String = "RH_PER_HORAS_EXTRAS"
    Public Const RH_PER_ESTADO_EMPLEADO As String = "RH_PER_ESTADO_EMPLEADO"
    Public Const RH_REM_GRADO As String = "RH_REM_GRADO"
    Public Const RH_PER_ESCALAFON As String = "RH_PER_ESCALAFON"
    Public Const RH_PER_ESTRUCTURA_ORGANICA As String = "RH_PER_ESTRUCTURA_ORGANICA"
    Public Const RH_PER_ESTRUCTURA_CONTABLE As String = "RH_PER_ESTRUCTURA_CONTABLE"
    Public Const RH_REM_ITEM As String = "RH_REM_ITEM"
    Public Const RH_REM_ITEM_AFECTO_ENDEUDAMIENTO As String = "RH_REM_ITEM_AFECTO_ENDEUDAMIENTO"
    Public Const RH_REM_TIPO_ITEM_ENDEUDAMIENTO As String = "RH_REM_TIPO_ITEM_ENDEUDAMIENTO"
    Public Const RH_REM_CENTRALIZACION As String = "RH_REM_CENTRALIZACION"
    Public Const RH_REM_CENTRALIZACION_IMPUTACION As String = "RH_REM_CENTRALIZACION_IMPUTACION"
    Public Const RH_REM_COLUMNA_LIBRO As String = "RH_REM_COLUMNA_LIBRO"
    Public Const RH_REM_CLASIFICACION_EMPLEADO As String = "RH_REM_CLASIFICACION_EMPLEADO"
    Public Const RH_REM_EUS As String = "RH_REM_EUS"
    Public Const RH_REM_EUS_ENC As String = "RH_REM_EUS_ENC"
    Public Const RH_REM_MOVIMIENTO_MENSUAL As String = "RH_REM_MOVIMIENTO_MENSUAL"
    Public Const RH_REM_LIQUIDACION As String = "RH_REM_LIQUIDACION"
    Public Const RH_REM_TXT_PLANO_PREVIRED As String = "RH_REM_TXT_PLANO_PREVIRED"
    Public Const GEN_RESPUESTA As String = "GEN_RESPUESTA"
    Public Const RH_REM_BONO_MODERNIZACION As String = "RH_REM_BONO_MODERNIZACION"
    Public Const RH_REM_RELIQUIDACION As String = "RH_REM_RELIQUIDACION"
    Public Const RH_PER_TIPO_JORNADA As String = "RH_PER_TIPO_JORNADA"
    Public Const RH_REM_SISTEMA_PREVISIONAL As String = "RH_REM_SISTEMA_PREVISIONAL"
    Public Const RH_REM_TIPO_TRABAJADOR_PREVIRED As String = "RH_REM_TIPO_TRABAJADOR_PREVIRED"
    Public Const RH_REM_REAJUSTE As String = "RH_REM_REAJUSTE"
    Public Const RH_PER_TIPO_BENEFICIARIO As String = "RH_PER_TIPO_BENEFICIARIO"
    Public Const RH_PER_TIPO_BENEFICIO As String = "RH_PER_TIPO_BENEFICIO"
    Public Const RH_PER_TIPO_CAUSANTE As String = "RH_PER_TIPO_CAUSANTE"
    Public Const RH_REM_ASIENTO_CONTABLE As String = "RH_REM_ASIENTO_CONTABLE"
    Public Const RH_REM_ASIENTO_CONTABLE_DETALLE As String = "RH_REM_ASIENTO_CONTABLE_DETALLE"
    Public Const RH_PER_CONTROL_ASISTENCIA As String = "RH_PER_CONTROL_ASISTENCIA"
    Public Const RH_REM_TIPO_ITEM As String = "RH_REM_TIPO_ITEM"
    Public Const RH_PER_EMISOR_CHEQUE As String = "RH_PER_EMISOR_CHEQUE"
    Public Const RH_PER_EMISOR_CHEQUE_DETALLE As String = "RH_PER_EMISOR_CHEQUE_DETALLE"
    Public Const RH_PER_ANTECEDENTE_HONORARIO_DETALLE As String = "RH_PER_ANTECEDENTE_HONORARIO_DETALLE"
    Public Const RH_PER_ANTECEDENTE_HONORARIO As String = "RH_PER_ANTECEDENTE_HONORARIO"
    Public Const RH_REM_TESORERIA_LIQ_PAGO As String = "RH_REM_TESORERIA_LIQ_PAGO"
    'Cargas Familiares
    Public Const RH_PER_TIPO_CARGA_FAM As String = "RH_PER_TIPO_CARGA_FAM"
    Public Const RH_PER_ESTADO_CARGA_FAM As String = "RH_PER_ESTADO_CARGA_FAM"
    Public Const RH_PER_GRUPO_FAMILIAR As String = "RH_PER_GRUPO_FAMILIAR"
    Public Const RH_PER_PARENTESCO As String = "RH_PER_PARENTESCO"
    Public Const RH_PER_CARGA_FAMILIAR As String = "RH_PER_CARGA_FAMILIAR"
    Public Const RH_PER_CAUSA_TERMINO_ASIG_FAM As String = "RH_PER_CAUSA_TERMINO_ASIG_FAM"
    'Fin Cargas Familiares
    'Viaticos
    Public Const RH_PER_VIATICO As String = "RH_PER_VIATICO"
    Public Const RH_PER_VIATICO_DETALLE As String = "RH_PER_VIATICO_DETALLE"
    'Fin Viaticos
    'Vistas
    Public Const VW_REM_ITEM_RELIQUIDADO As String = "VW_REM_ITEM_RELIQUIDADO"
    Public Const RH_PER_UBICACION_FISICA As String = "RH_PER_UBICACION_FISICA"
    Public Const RH_PER_PARENTESCO_FALLECIMIENTO As String = "RH_PER_PARENTESCO_FALLECIMIENTO"

End Class


