'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DSCargaFamiliar"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DSCargaFamiliar
    Inherits Global.System.Data.DataSet
    
    Private tableRH_PER_CARGA_FAMILIAR As RH_PER_CARGA_FAMILIARDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("RH_PER_CARGA_FAMILIAR")) Is Nothing) Then
                MyBase.Tables.Add(New RH_PER_CARGA_FAMILIARDataTable(ds.Tables("RH_PER_CARGA_FAMILIAR")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property RH_PER_CARGA_FAMILIAR() As RH_PER_CARGA_FAMILIARDataTable
        Get
            Return Me.tableRH_PER_CARGA_FAMILIAR
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DSCargaFamiliar = CType(MyBase.Clone,DSCargaFamiliar)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("RH_PER_CARGA_FAMILIAR")) Is Nothing) Then
                MyBase.Tables.Add(New RH_PER_CARGA_FAMILIARDataTable(ds.Tables("RH_PER_CARGA_FAMILIAR")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableRH_PER_CARGA_FAMILIAR = CType(MyBase.Tables("RH_PER_CARGA_FAMILIAR"),RH_PER_CARGA_FAMILIARDataTable)
        If (initTable = true) Then
            If (Not (Me.tableRH_PER_CARGA_FAMILIAR) Is Nothing) Then
                Me.tableRH_PER_CARGA_FAMILIAR.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "DSCargaFamiliar"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DSCargaFamiliar.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableRH_PER_CARGA_FAMILIAR = New RH_PER_CARGA_FAMILIARDataTable()
        MyBase.Tables.Add(Me.tableRH_PER_CARGA_FAMILIAR)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializeRH_PER_CARGA_FAMILIAR() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DSCargaFamiliar = New DSCargaFamiliar()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub RH_PER_CARGA_FAMILIARRowChangeEventHandler(ByVal sender As Object, ByVal e As RH_PER_CARGA_FAMILIARRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class RH_PER_CARGA_FAMILIARDataTable
        Inherits Global.System.Data.TypedTableBase(Of RH_PER_CARGA_FAMILIARRow)
        
        Private columnCARGA_FAMILIAR_ID As Global.System.Data.DataColumn
        
        Private columnEMPLEADO_ID As Global.System.Data.DataColumn
        
        Private columnNIVEL_ESTUDIO_ID As Global.System.Data.DataColumn
        
        Private columnTIPO_CARGA_FAM_ID As Global.System.Data.DataColumn
        
        Private columnPARENTESCO_ID As Global.System.Data.DataColumn
        
        Private columnGRUPO_FAMILIAR_ID As Global.System.Data.DataColumn
        
        Private columnRUT_CARGA As Global.System.Data.DataColumn
        
        Private columnDIGITO_VER_CARGA As Global.System.Data.DataColumn
        
        Private columnAPELLIDO_PAT_CARGA As Global.System.Data.DataColumn
        
        Private columnAPELLIDO_MAT_CARGA As Global.System.Data.DataColumn
        
        Private columnNOMBRES_CARGA As Global.System.Data.DataColumn
        
        Private columnSEXO_CARGA As Global.System.Data.DataColumn
        
        Private columnFECHA_NACIMIENTO As Global.System.Data.DataColumn
        
        Private columnESTADO_CARGA_ID As Global.System.Data.DataColumn
        
        Private columnFECHA_VIGENCIA As Global.System.Data.DataColumn
        
        Private columnFECHA_VENCIMIENTO As Global.System.Data.DataColumn
        
        Private columnRETENSION_JUDICIAL As Global.System.Data.DataColumn
        
        Private columnCARGA_POR_ESTUDIO As Global.System.Data.DataColumn
        
        Private columnCAUSA_TERMINO_ASIG_FAM_ID As Global.System.Data.DataColumn
        
        Private columnESTADO_REGISTRO As Global.System.Data.DataColumn
        
        Private columnTIPO_BENEFICIO_ID As Global.System.Data.DataColumn
        
        Private columnTIPO_CAUSANTE_ID As Global.System.Data.DataColumn
        
        Private columnXML_CARGACAUSANTE As Global.System.Data.DataColumn
        
        Private columnXML_RESPUESTACARGACAUSANTE As Global.System.Data.DataColumn
        
        Private columnUSUARIO As Global.System.Data.DataColumn
        
        Private columnFECHA_MODIFICACION As Global.System.Data.DataColumn
        
        Private columnHORA_MODIFICACION As Global.System.Data.DataColumn
        
        Private columnREGIMEN_ESTUDIO As Global.System.Data.DataColumn
        
        Private columnFECHA_INICIO_RECONOCIMIENTO As Global.System.Data.DataColumn
        
        Private columnFECHA_FIN_RECONOCIMIENTO As Global.System.Data.DataColumn
        
        Private columnNUMERO_RESOLUCION As Global.System.Data.DataColumn
        
        Private columnPERIODO_ID As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "RH_PER_CARGA_FAMILIAR"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CARGA_FAMILIAR_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCARGA_FAMILIAR_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property EMPLEADO_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEMPLEADO_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property NIVEL_ESTUDIO_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNIVEL_ESTUDIO_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TIPO_CARGA_FAM_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTIPO_CARGA_FAM_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PARENTESCO_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPARENTESCO_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property GRUPO_FAMILIAR_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGRUPO_FAMILIAR_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property RUT_CARGAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRUT_CARGA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DIGITO_VER_CARGAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDIGITO_VER_CARGA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property APELLIDO_PAT_CARGAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAPELLIDO_PAT_CARGA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property APELLIDO_MAT_CARGAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAPELLIDO_MAT_CARGA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property NOMBRES_CARGAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNOMBRES_CARGA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SEXO_CARGAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSEXO_CARGA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FECHA_NACIMIENTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFECHA_NACIMIENTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ESTADO_CARGA_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnESTADO_CARGA_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FECHA_VIGENCIAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFECHA_VIGENCIA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FECHA_VENCIMIENTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFECHA_VENCIMIENTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property RETENSION_JUDICIALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRETENSION_JUDICIAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CARGA_POR_ESTUDIOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCARGA_POR_ESTUDIO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CAUSA_TERMINO_ASIG_FAM_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCAUSA_TERMINO_ASIG_FAM_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ESTADO_REGISTROColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnESTADO_REGISTRO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TIPO_BENEFICIO_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTIPO_BENEFICIO_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TIPO_CAUSANTE_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTIPO_CAUSANTE_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property XML_CARGACAUSANTEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnXML_CARGACAUSANTE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property XML_RESPUESTACARGACAUSANTEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnXML_RESPUESTACARGACAUSANTE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property USUARIOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUSUARIO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FECHA_MODIFICACIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFECHA_MODIFICACION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORA_MODIFICACIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORA_MODIFICACION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property REGIMEN_ESTUDIOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnREGIMEN_ESTUDIO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FECHA_INICIO_RECONOCIMIENTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFECHA_INICIO_RECONOCIMIENTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FECHA_FIN_RECONOCIMIENTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFECHA_FIN_RECONOCIMIENTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property NUMERO_RESOLUCIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNUMERO_RESOLUCION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PERIODO_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPERIODO_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As RH_PER_CARGA_FAMILIARRow
            Get
                Return CType(Me.Rows(index),RH_PER_CARGA_FAMILIARRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event RH_PER_CARGA_FAMILIARRowChanging As RH_PER_CARGA_FAMILIARRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event RH_PER_CARGA_FAMILIARRowChanged As RH_PER_CARGA_FAMILIARRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event RH_PER_CARGA_FAMILIARRowDeleting As RH_PER_CARGA_FAMILIARRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event RH_PER_CARGA_FAMILIARRowDeleted As RH_PER_CARGA_FAMILIARRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub AddRH_PER_CARGA_FAMILIARRow(ByVal row As RH_PER_CARGA_FAMILIARRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function AddRH_PER_CARGA_FAMILIARRow( _
                    ByVal EMPLEADO_ID As Integer,  _
                    ByVal NIVEL_ESTUDIO_ID As Integer,  _
                    ByVal TIPO_CARGA_FAM_ID As Integer,  _
                    ByVal PARENTESCO_ID As Integer,  _
                    ByVal GRUPO_FAMILIAR_ID As Byte,  _
                    ByVal RUT_CARGA As Integer,  _
                    ByVal DIGITO_VER_CARGA As String,  _
                    ByVal APELLIDO_PAT_CARGA As String,  _
                    ByVal APELLIDO_MAT_CARGA As String,  _
                    ByVal NOMBRES_CARGA As String,  _
                    ByVal SEXO_CARGA As String,  _
                    ByVal FECHA_NACIMIENTO As Date,  _
                    ByVal ESTADO_CARGA_ID As Byte,  _
                    ByVal FECHA_VIGENCIA As Date,  _
                    ByVal FECHA_VENCIMIENTO As Date,  _
                    ByVal RETENSION_JUDICIAL As String,  _
                    ByVal CARGA_POR_ESTUDIO As String,  _
                    ByVal CAUSA_TERMINO_ASIG_FAM_ID As Byte,  _
                    ByVal ESTADO_REGISTRO As Byte,  _
                    ByVal TIPO_BENEFICIO_ID As Integer,  _
                    ByVal TIPO_CAUSANTE_ID As Integer,  _
                    ByVal XML_CARGACAUSANTE As String,  _
                    ByVal XML_RESPUESTACARGACAUSANTE As String,  _
                    ByVal USUARIO As String,  _
                    ByVal FECHA_MODIFICACION As Date,  _
                    ByVal HORA_MODIFICACION As String,  _
                    ByVal REGIMEN_ESTUDIO As Integer,  _
                    ByVal FECHA_INICIO_RECONOCIMIENTO As Date,  _
                    ByVal FECHA_FIN_RECONOCIMIENTO As Date,  _
                    ByVal NUMERO_RESOLUCION As String,  _
                    ByVal PERIODO_ID As Integer) As RH_PER_CARGA_FAMILIARRow
            Dim rowRH_PER_CARGA_FAMILIARRow As RH_PER_CARGA_FAMILIARRow = CType(Me.NewRow,RH_PER_CARGA_FAMILIARRow)
            Dim columnValuesArray() As Object = New Object() {Nothing, EMPLEADO_ID, NIVEL_ESTUDIO_ID, TIPO_CARGA_FAM_ID, PARENTESCO_ID, GRUPO_FAMILIAR_ID, RUT_CARGA, DIGITO_VER_CARGA, APELLIDO_PAT_CARGA, APELLIDO_MAT_CARGA, NOMBRES_CARGA, SEXO_CARGA, FECHA_NACIMIENTO, ESTADO_CARGA_ID, FECHA_VIGENCIA, FECHA_VENCIMIENTO, RETENSION_JUDICIAL, CARGA_POR_ESTUDIO, CAUSA_TERMINO_ASIG_FAM_ID, ESTADO_REGISTRO, TIPO_BENEFICIO_ID, TIPO_CAUSANTE_ID, XML_CARGACAUSANTE, XML_RESPUESTACARGACAUSANTE, USUARIO, FECHA_MODIFICACION, HORA_MODIFICACION, REGIMEN_ESTUDIO, FECHA_INICIO_RECONOCIMIENTO, FECHA_FIN_RECONOCIMIENTO, NUMERO_RESOLUCION, PERIODO_ID}
            rowRH_PER_CARGA_FAMILIARRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowRH_PER_CARGA_FAMILIARRow)
            Return rowRH_PER_CARGA_FAMILIARRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function FindByCARGA_FAMILIAR_ID(ByVal CARGA_FAMILIAR_ID As Integer) As RH_PER_CARGA_FAMILIARRow
            Return CType(Me.Rows.Find(New Object() {CARGA_FAMILIAR_ID}),RH_PER_CARGA_FAMILIARRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As RH_PER_CARGA_FAMILIARDataTable = CType(MyBase.Clone,RH_PER_CARGA_FAMILIARDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New RH_PER_CARGA_FAMILIARDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnCARGA_FAMILIAR_ID = MyBase.Columns("CARGA_FAMILIAR_ID")
            Me.columnEMPLEADO_ID = MyBase.Columns("EMPLEADO_ID")
            Me.columnNIVEL_ESTUDIO_ID = MyBase.Columns("NIVEL_ESTUDIO_ID")
            Me.columnTIPO_CARGA_FAM_ID = MyBase.Columns("TIPO_CARGA_FAM_ID")
            Me.columnPARENTESCO_ID = MyBase.Columns("PARENTESCO_ID")
            Me.columnGRUPO_FAMILIAR_ID = MyBase.Columns("GRUPO_FAMILIAR_ID")
            Me.columnRUT_CARGA = MyBase.Columns("RUT_CARGA")
            Me.columnDIGITO_VER_CARGA = MyBase.Columns("DIGITO_VER_CARGA")
            Me.columnAPELLIDO_PAT_CARGA = MyBase.Columns("APELLIDO_PAT_CARGA")
            Me.columnAPELLIDO_MAT_CARGA = MyBase.Columns("APELLIDO_MAT_CARGA")
            Me.columnNOMBRES_CARGA = MyBase.Columns("NOMBRES_CARGA")
            Me.columnSEXO_CARGA = MyBase.Columns("SEXO_CARGA")
            Me.columnFECHA_NACIMIENTO = MyBase.Columns("FECHA_NACIMIENTO")
            Me.columnESTADO_CARGA_ID = MyBase.Columns("ESTADO_CARGA_ID")
            Me.columnFECHA_VIGENCIA = MyBase.Columns("FECHA_VIGENCIA")
            Me.columnFECHA_VENCIMIENTO = MyBase.Columns("FECHA_VENCIMIENTO")
            Me.columnRETENSION_JUDICIAL = MyBase.Columns("RETENSION_JUDICIAL")
            Me.columnCARGA_POR_ESTUDIO = MyBase.Columns("CARGA_POR_ESTUDIO")
            Me.columnCAUSA_TERMINO_ASIG_FAM_ID = MyBase.Columns("CAUSA_TERMINO_ASIG_FAM_ID")
            Me.columnESTADO_REGISTRO = MyBase.Columns("ESTADO_REGISTRO")
            Me.columnTIPO_BENEFICIO_ID = MyBase.Columns("TIPO_BENEFICIO_ID")
            Me.columnTIPO_CAUSANTE_ID = MyBase.Columns("TIPO_CAUSANTE_ID")
            Me.columnXML_CARGACAUSANTE = MyBase.Columns("XML_CARGACAUSANTE")
            Me.columnXML_RESPUESTACARGACAUSANTE = MyBase.Columns("XML_RESPUESTACARGACAUSANTE")
            Me.columnUSUARIO = MyBase.Columns("USUARIO")
            Me.columnFECHA_MODIFICACION = MyBase.Columns("FECHA_MODIFICACION")
            Me.columnHORA_MODIFICACION = MyBase.Columns("HORA_MODIFICACION")
            Me.columnREGIMEN_ESTUDIO = MyBase.Columns("REGIMEN_ESTUDIO")
            Me.columnFECHA_INICIO_RECONOCIMIENTO = MyBase.Columns("FECHA_INICIO_RECONOCIMIENTO")
            Me.columnFECHA_FIN_RECONOCIMIENTO = MyBase.Columns("FECHA_FIN_RECONOCIMIENTO")
            Me.columnNUMERO_RESOLUCION = MyBase.Columns("NUMERO_RESOLUCION")
            Me.columnPERIODO_ID = MyBase.Columns("PERIODO_ID")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnCARGA_FAMILIAR_ID = New Global.System.Data.DataColumn("CARGA_FAMILIAR_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCARGA_FAMILIAR_ID)
            Me.columnEMPLEADO_ID = New Global.System.Data.DataColumn("EMPLEADO_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEMPLEADO_ID)
            Me.columnNIVEL_ESTUDIO_ID = New Global.System.Data.DataColumn("NIVEL_ESTUDIO_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNIVEL_ESTUDIO_ID)
            Me.columnTIPO_CARGA_FAM_ID = New Global.System.Data.DataColumn("TIPO_CARGA_FAM_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTIPO_CARGA_FAM_ID)
            Me.columnPARENTESCO_ID = New Global.System.Data.DataColumn("PARENTESCO_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPARENTESCO_ID)
            Me.columnGRUPO_FAMILIAR_ID = New Global.System.Data.DataColumn("GRUPO_FAMILIAR_ID", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGRUPO_FAMILIAR_ID)
            Me.columnRUT_CARGA = New Global.System.Data.DataColumn("RUT_CARGA", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRUT_CARGA)
            Me.columnDIGITO_VER_CARGA = New Global.System.Data.DataColumn("DIGITO_VER_CARGA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDIGITO_VER_CARGA)
            Me.columnAPELLIDO_PAT_CARGA = New Global.System.Data.DataColumn("APELLIDO_PAT_CARGA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAPELLIDO_PAT_CARGA)
            Me.columnAPELLIDO_MAT_CARGA = New Global.System.Data.DataColumn("APELLIDO_MAT_CARGA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAPELLIDO_MAT_CARGA)
            Me.columnNOMBRES_CARGA = New Global.System.Data.DataColumn("NOMBRES_CARGA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNOMBRES_CARGA)
            Me.columnSEXO_CARGA = New Global.System.Data.DataColumn("SEXO_CARGA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSEXO_CARGA)
            Me.columnFECHA_NACIMIENTO = New Global.System.Data.DataColumn("FECHA_NACIMIENTO", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFECHA_NACIMIENTO)
            Me.columnESTADO_CARGA_ID = New Global.System.Data.DataColumn("ESTADO_CARGA_ID", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnESTADO_CARGA_ID)
            Me.columnFECHA_VIGENCIA = New Global.System.Data.DataColumn("FECHA_VIGENCIA", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFECHA_VIGENCIA)
            Me.columnFECHA_VENCIMIENTO = New Global.System.Data.DataColumn("FECHA_VENCIMIENTO", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFECHA_VENCIMIENTO)
            Me.columnRETENSION_JUDICIAL = New Global.System.Data.DataColumn("RETENSION_JUDICIAL", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRETENSION_JUDICIAL)
            Me.columnCARGA_POR_ESTUDIO = New Global.System.Data.DataColumn("CARGA_POR_ESTUDIO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCARGA_POR_ESTUDIO)
            Me.columnCAUSA_TERMINO_ASIG_FAM_ID = New Global.System.Data.DataColumn("CAUSA_TERMINO_ASIG_FAM_ID", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCAUSA_TERMINO_ASIG_FAM_ID)
            Me.columnESTADO_REGISTRO = New Global.System.Data.DataColumn("ESTADO_REGISTRO", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnESTADO_REGISTRO)
            Me.columnTIPO_BENEFICIO_ID = New Global.System.Data.DataColumn("TIPO_BENEFICIO_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTIPO_BENEFICIO_ID)
            Me.columnTIPO_CAUSANTE_ID = New Global.System.Data.DataColumn("TIPO_CAUSANTE_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTIPO_CAUSANTE_ID)
            Me.columnXML_CARGACAUSANTE = New Global.System.Data.DataColumn("XML_CARGACAUSANTE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnXML_CARGACAUSANTE)
            Me.columnXML_RESPUESTACARGACAUSANTE = New Global.System.Data.DataColumn("XML_RESPUESTACARGACAUSANTE", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnXML_RESPUESTACARGACAUSANTE)
            Me.columnUSUARIO = New Global.System.Data.DataColumn("USUARIO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUSUARIO)
            Me.columnFECHA_MODIFICACION = New Global.System.Data.DataColumn("FECHA_MODIFICACION", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFECHA_MODIFICACION)
            Me.columnHORA_MODIFICACION = New Global.System.Data.DataColumn("HORA_MODIFICACION", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORA_MODIFICACION)
            Me.columnREGIMEN_ESTUDIO = New Global.System.Data.DataColumn("REGIMEN_ESTUDIO", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnREGIMEN_ESTUDIO)
            Me.columnFECHA_INICIO_RECONOCIMIENTO = New Global.System.Data.DataColumn("FECHA_INICIO_RECONOCIMIENTO", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFECHA_INICIO_RECONOCIMIENTO)
            Me.columnFECHA_FIN_RECONOCIMIENTO = New Global.System.Data.DataColumn("FECHA_FIN_RECONOCIMIENTO", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFECHA_FIN_RECONOCIMIENTO)
            Me.columnNUMERO_RESOLUCION = New Global.System.Data.DataColumn("NUMERO_RESOLUCION", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNUMERO_RESOLUCION)
            Me.columnPERIODO_ID = New Global.System.Data.DataColumn("PERIODO_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPERIODO_ID)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("DSCargaFamiliarKey1", New Global.System.Data.DataColumn() {Me.columnCARGA_FAMILIAR_ID}, true))
            Me.columnCARGA_FAMILIAR_ID.AutoIncrement = true
            Me.columnCARGA_FAMILIAR_ID.AllowDBNull = false
            Me.columnCARGA_FAMILIAR_ID.ReadOnly = true
            Me.columnCARGA_FAMILIAR_ID.Unique = true
            Me.columnEMPLEADO_ID.AllowDBNull = false
            Me.columnNIVEL_ESTUDIO_ID.AllowDBNull = false
            Me.columnTIPO_CARGA_FAM_ID.AllowDBNull = false
            Me.columnPARENTESCO_ID.AllowDBNull = false
            Me.columnGRUPO_FAMILIAR_ID.AllowDBNull = false
            Me.columnRUT_CARGA.AllowDBNull = false
            Me.columnDIGITO_VER_CARGA.AllowDBNull = false
            Me.columnAPELLIDO_PAT_CARGA.AllowDBNull = false
            Me.columnAPELLIDO_MAT_CARGA.AllowDBNull = false
            Me.columnNOMBRES_CARGA.AllowDBNull = false
            Me.columnSEXO_CARGA.AllowDBNull = false
            Me.columnFECHA_NACIMIENTO.AllowDBNull = false
            Me.columnESTADO_CARGA_ID.AllowDBNull = false
            Me.columnRETENSION_JUDICIAL.AllowDBNull = false
            Me.columnCARGA_POR_ESTUDIO.AllowDBNull = false
            Me.columnCAUSA_TERMINO_ASIG_FAM_ID.AllowDBNull = false
            Me.columnUSUARIO.AllowDBNull = false
            Me.columnFECHA_MODIFICACION.AllowDBNull = false
            Me.columnHORA_MODIFICACION.AllowDBNull = false
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function NewRH_PER_CARGA_FAMILIARRow() As RH_PER_CARGA_FAMILIARRow
            Return CType(Me.NewRow,RH_PER_CARGA_FAMILIARRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New RH_PER_CARGA_FAMILIARRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(RH_PER_CARGA_FAMILIARRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.RH_PER_CARGA_FAMILIARRowChangedEvent) Is Nothing) Then
                RaiseEvent RH_PER_CARGA_FAMILIARRowChanged(Me, New RH_PER_CARGA_FAMILIARRowChangeEvent(CType(e.Row,RH_PER_CARGA_FAMILIARRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.RH_PER_CARGA_FAMILIARRowChangingEvent) Is Nothing) Then
                RaiseEvent RH_PER_CARGA_FAMILIARRowChanging(Me, New RH_PER_CARGA_FAMILIARRowChangeEvent(CType(e.Row,RH_PER_CARGA_FAMILIARRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.RH_PER_CARGA_FAMILIARRowDeletedEvent) Is Nothing) Then
                RaiseEvent RH_PER_CARGA_FAMILIARRowDeleted(Me, New RH_PER_CARGA_FAMILIARRowChangeEvent(CType(e.Row,RH_PER_CARGA_FAMILIARRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.RH_PER_CARGA_FAMILIARRowDeletingEvent) Is Nothing) Then
                RaiseEvent RH_PER_CARGA_FAMILIARRowDeleting(Me, New RH_PER_CARGA_FAMILIARRowChangeEvent(CType(e.Row,RH_PER_CARGA_FAMILIARRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub RemoveRH_PER_CARGA_FAMILIARRow(ByVal row As RH_PER_CARGA_FAMILIARRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As DSCargaFamiliar = New DSCargaFamiliar()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "RH_PER_CARGA_FAMILIARDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class RH_PER_CARGA_FAMILIARRow
        Inherits Global.System.Data.DataRow
        
        Private tableRH_PER_CARGA_FAMILIAR As RH_PER_CARGA_FAMILIARDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableRH_PER_CARGA_FAMILIAR = CType(Me.Table,RH_PER_CARGA_FAMILIARDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CARGA_FAMILIAR_ID() As Integer
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.CARGA_FAMILIAR_IDColumn),Integer)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.CARGA_FAMILIAR_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property EMPLEADO_ID() As Integer
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.EMPLEADO_IDColumn),Integer)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.EMPLEADO_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property NIVEL_ESTUDIO_ID() As Integer
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.NIVEL_ESTUDIO_IDColumn),Integer)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.NIVEL_ESTUDIO_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TIPO_CARGA_FAM_ID() As Integer
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.TIPO_CARGA_FAM_IDColumn),Integer)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.TIPO_CARGA_FAM_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PARENTESCO_ID() As Integer
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.PARENTESCO_IDColumn),Integer)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.PARENTESCO_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property GRUPO_FAMILIAR_ID() As Byte
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.GRUPO_FAMILIAR_IDColumn),Byte)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.GRUPO_FAMILIAR_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property RUT_CARGA() As Integer
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.RUT_CARGAColumn),Integer)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.RUT_CARGAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DIGITO_VER_CARGA() As String
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.DIGITO_VER_CARGAColumn),String)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.DIGITO_VER_CARGAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property APELLIDO_PAT_CARGA() As String
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.APELLIDO_PAT_CARGAColumn),String)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.APELLIDO_PAT_CARGAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property APELLIDO_MAT_CARGA() As String
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.APELLIDO_MAT_CARGAColumn),String)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.APELLIDO_MAT_CARGAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property NOMBRES_CARGA() As String
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.NOMBRES_CARGAColumn),String)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.NOMBRES_CARGAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SEXO_CARGA() As String
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.SEXO_CARGAColumn),String)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.SEXO_CARGAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FECHA_NACIMIENTO() As Date
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_NACIMIENTOColumn),Date)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_NACIMIENTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ESTADO_CARGA_ID() As Byte
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.ESTADO_CARGA_IDColumn),Byte)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.ESTADO_CARGA_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FECHA_VIGENCIA() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_VIGENCIAColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FECHA_VIGENCIA' in table 'RH_PER_CARGA_FAMILIAR' is DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_VIGENCIAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FECHA_VENCIMIENTO() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_VENCIMIENTOColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FECHA_VENCIMIENTO' in table 'RH_PER_CARGA_FAMILIAR' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_VENCIMIENTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property RETENSION_JUDICIAL() As String
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.RETENSION_JUDICIALColumn),String)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.RETENSION_JUDICIALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CARGA_POR_ESTUDIO() As String
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.CARGA_POR_ESTUDIOColumn),String)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.CARGA_POR_ESTUDIOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CAUSA_TERMINO_ASIG_FAM_ID() As Byte
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.CAUSA_TERMINO_ASIG_FAM_IDColumn),Byte)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.CAUSA_TERMINO_ASIG_FAM_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ESTADO_REGISTRO() As Byte
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.ESTADO_REGISTROColumn),Byte)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ESTADO_REGISTRO' in table 'RH_PER_CARGA_FAMILIAR' is DBNull"& _ 
                            ".", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.ESTADO_REGISTROColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TIPO_BENEFICIO_ID() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.TIPO_BENEFICIO_IDColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TIPO_BENEFICIO_ID' in table 'RH_PER_CARGA_FAMILIAR' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.TIPO_BENEFICIO_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TIPO_CAUSANTE_ID() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.TIPO_CAUSANTE_IDColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TIPO_CAUSANTE_ID' in table 'RH_PER_CARGA_FAMILIAR' is DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.TIPO_CAUSANTE_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property XML_CARGACAUSANTE() As String
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.XML_CARGACAUSANTEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'XML_CARGACAUSANTE' in table 'RH_PER_CARGA_FAMILIAR' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.XML_CARGACAUSANTEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property XML_RESPUESTACARGACAUSANTE() As String
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.XML_RESPUESTACARGACAUSANTEColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'XML_RESPUESTACARGACAUSANTE' in table 'RH_PER_CARGA_FAMILIAR"& _ 
                            "' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.XML_RESPUESTACARGACAUSANTEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property USUARIO() As String
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.USUARIOColumn),String)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.USUARIOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FECHA_MODIFICACION() As Date
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_MODIFICACIONColumn),Date)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_MODIFICACIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORA_MODIFICACION() As String
            Get
                Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.HORA_MODIFICACIONColumn),String)
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.HORA_MODIFICACIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property REGIMEN_ESTUDIO() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.REGIMEN_ESTUDIOColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'REGIMEN_ESTUDIO' in table 'RH_PER_CARGA_FAMILIAR' is DBNull"& _ 
                            ".", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.REGIMEN_ESTUDIOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FECHA_INICIO_RECONOCIMIENTO() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_INICIO_RECONOCIMIENTOColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FECHA_INICIO_RECONOCIMIENTO' in table 'RH_PER_CARGA_FAMILIA"& _ 
                            "R' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_INICIO_RECONOCIMIENTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FECHA_FIN_RECONOCIMIENTO() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_FIN_RECONOCIMIENTOColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FECHA_FIN_RECONOCIMIENTO' in table 'RH_PER_CARGA_FAMILIAR' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_FIN_RECONOCIMIENTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property NUMERO_RESOLUCION() As String
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.NUMERO_RESOLUCIONColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'NUMERO_RESOLUCION' in table 'RH_PER_CARGA_FAMILIAR' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.NUMERO_RESOLUCIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PERIODO_ID() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CARGA_FAMILIAR.PERIODO_IDColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PERIODO_ID' in table 'RH_PER_CARGA_FAMILIAR' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CARGA_FAMILIAR.PERIODO_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsFECHA_VIGENCIANull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_VIGENCIAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetFECHA_VIGENCIANull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_VIGENCIAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsFECHA_VENCIMIENTONull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_VENCIMIENTOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetFECHA_VENCIMIENTONull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_VENCIMIENTOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsESTADO_REGISTRONull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.ESTADO_REGISTROColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetESTADO_REGISTRONull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.ESTADO_REGISTROColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTIPO_BENEFICIO_IDNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.TIPO_BENEFICIO_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTIPO_BENEFICIO_IDNull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.TIPO_BENEFICIO_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTIPO_CAUSANTE_IDNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.TIPO_CAUSANTE_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTIPO_CAUSANTE_IDNull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.TIPO_CAUSANTE_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsXML_CARGACAUSANTENull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.XML_CARGACAUSANTEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetXML_CARGACAUSANTENull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.XML_CARGACAUSANTEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsXML_RESPUESTACARGACAUSANTENull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.XML_RESPUESTACARGACAUSANTEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetXML_RESPUESTACARGACAUSANTENull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.XML_RESPUESTACARGACAUSANTEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsREGIMEN_ESTUDIONull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.REGIMEN_ESTUDIOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetREGIMEN_ESTUDIONull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.REGIMEN_ESTUDIOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsFECHA_INICIO_RECONOCIMIENTONull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_INICIO_RECONOCIMIENTOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetFECHA_INICIO_RECONOCIMIENTONull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_INICIO_RECONOCIMIENTOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsFECHA_FIN_RECONOCIMIENTONull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_FIN_RECONOCIMIENTOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetFECHA_FIN_RECONOCIMIENTONull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.FECHA_FIN_RECONOCIMIENTOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsNUMERO_RESOLUCIONNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.NUMERO_RESOLUCIONColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetNUMERO_RESOLUCIONNull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.NUMERO_RESOLUCIONColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPERIODO_IDNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CARGA_FAMILIAR.PERIODO_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPERIODO_IDNull()
            Me(Me.tableRH_PER_CARGA_FAMILIAR.PERIODO_IDColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class RH_PER_CARGA_FAMILIARRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As RH_PER_CARGA_FAMILIARRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As RH_PER_CARGA_FAMILIARRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As RH_PER_CARGA_FAMILIARRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
