'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DSControlAsistencia"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DSControlAsistencia
    Inherits Global.System.Data.DataSet
    
    Private tableRH_PER_CONTROL_ASISTENCIA As RH_PER_CONTROL_ASISTENCIADataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("RH_PER_CONTROL_ASISTENCIA")) Is Nothing) Then
                MyBase.Tables.Add(New RH_PER_CONTROL_ASISTENCIADataTable(ds.Tables("RH_PER_CONTROL_ASISTENCIA")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property RH_PER_CONTROL_ASISTENCIA() As RH_PER_CONTROL_ASISTENCIADataTable
        Get
            Return Me.tableRH_PER_CONTROL_ASISTENCIA
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DSControlAsistencia = CType(MyBase.Clone,DSControlAsistencia)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("RH_PER_CONTROL_ASISTENCIA")) Is Nothing) Then
                MyBase.Tables.Add(New RH_PER_CONTROL_ASISTENCIADataTable(ds.Tables("RH_PER_CONTROL_ASISTENCIA")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableRH_PER_CONTROL_ASISTENCIA = CType(MyBase.Tables("RH_PER_CONTROL_ASISTENCIA"),RH_PER_CONTROL_ASISTENCIADataTable)
        If (initTable = true) Then
            If (Not (Me.tableRH_PER_CONTROL_ASISTENCIA) Is Nothing) Then
                Me.tableRH_PER_CONTROL_ASISTENCIA.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "DSControlAsistencia"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DSControlAsistencia.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableRH_PER_CONTROL_ASISTENCIA = New RH_PER_CONTROL_ASISTENCIADataTable()
        MyBase.Tables.Add(Me.tableRH_PER_CONTROL_ASISTENCIA)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializeRH_PER_CONTROL_ASISTENCIA() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DSControlAsistencia = New DSControlAsistencia()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub RH_PER_CONTROL_ASISTENCIARowChangeEventHandler(ByVal sender As Object, ByVal e As RH_PER_CONTROL_ASISTENCIARowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class RH_PER_CONTROL_ASISTENCIADataTable
        Inherits Global.System.Data.TypedTableBase(Of RH_PER_CONTROL_ASISTENCIARow)
        
        Private columnASISTENCIA_ID As Global.System.Data.DataColumn
        
        Private columnEMPLEADO_ID As Global.System.Data.DataColumn
        
        Private columnPERIODO_ID As Global.System.Data.DataColumn
        
        Private columnFECHA_ASISTENCIA As Global.System.Data.DataColumn
        
        Private columnHORA_ENTRADA As Global.System.Data.DataColumn
        
        Private columnHORA_SALIDA As Global.System.Data.DataColumn
        
        Private columnHORAS_TRABAJADAS As Global.System.Data.DataColumn
        
        Private columnHORAS_EXTRAS_DIURNAS As Global.System.Data.DataColumn
        
        Private columnHORAS_EXTRAS_NOCTURNAS As Global.System.Data.DataColumn
        
        Private columnMEDIO_DIA As Global.System.Data.DataColumn
        
        Private columnHORAS_ATRASOS As Global.System.Data.DataColumn
        
        Private columnHORAS_EXTRAS_DIURNAS_AUTORIZADAS As Global.System.Data.DataColumn
        
        Private columnHORAS_EXTRAS_NOCTURNAS_AUTORIZADAS As Global.System.Data.DataColumn
        
        Private columnMEDIO_DIA_AUTORIZADO As Global.System.Data.DataColumn
        
        Private columnTIPO_EVENTO_ADMIN_ID As Global.System.Data.DataColumn
        
        Private columnHORAS_ATRASOS_AUTORIZADOS As Global.System.Data.DataColumn
        
        Private columnANO_REAL As Global.System.Data.DataColumn
        
        Private columnMES_REAL As Global.System.Data.DataColumn
        
        Private columnOBSERVACIONES As Global.System.Data.DataColumn
        
        Private columnFECHA_MODIFICACION As Global.System.Data.DataColumn
        
        Private columnUSUARIO As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "RH_PER_CONTROL_ASISTENCIA"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ASISTENCIA_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnASISTENCIA_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property EMPLEADO_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEMPLEADO_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PERIODO_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPERIODO_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FECHA_ASISTENCIAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFECHA_ASISTENCIA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORA_ENTRADAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORA_ENTRADA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORA_SALIDAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORA_SALIDA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORAS_TRABAJADASColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORAS_TRABAJADAS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORAS_EXTRAS_DIURNASColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORAS_EXTRAS_DIURNAS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORAS_EXTRAS_NOCTURNASColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORAS_EXTRAS_NOCTURNAS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MEDIO_DIAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMEDIO_DIA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORAS_ATRASOSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORAS_ATRASOS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORAS_EXTRAS_DIURNAS_AUTORIZADASColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORAS_EXTRAS_DIURNAS_AUTORIZADAS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORAS_EXTRAS_NOCTURNAS_AUTORIZADASColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORAS_EXTRAS_NOCTURNAS_AUTORIZADAS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MEDIO_DIA_AUTORIZADOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMEDIO_DIA_AUTORIZADO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TIPO_EVENTO_ADMIN_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTIPO_EVENTO_ADMIN_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORAS_ATRASOS_AUTORIZADOSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORAS_ATRASOS_AUTORIZADOS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ANO_REALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnANO_REAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MES_REALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMES_REAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property OBSERVACIONESColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnOBSERVACIONES
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FECHA_MODIFICACIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFECHA_MODIFICACION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property USUARIOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUSUARIO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As RH_PER_CONTROL_ASISTENCIARow
            Get
                Return CType(Me.Rows(index),RH_PER_CONTROL_ASISTENCIARow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event RH_PER_CONTROL_ASISTENCIARowChanging As RH_PER_CONTROL_ASISTENCIARowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event RH_PER_CONTROL_ASISTENCIARowChanged As RH_PER_CONTROL_ASISTENCIARowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event RH_PER_CONTROL_ASISTENCIARowDeleting As RH_PER_CONTROL_ASISTENCIARowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event RH_PER_CONTROL_ASISTENCIARowDeleted As RH_PER_CONTROL_ASISTENCIARowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub AddRH_PER_CONTROL_ASISTENCIARow(ByVal row As RH_PER_CONTROL_ASISTENCIARow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function AddRH_PER_CONTROL_ASISTENCIARow( _
                    ByVal EMPLEADO_ID As Short,  _
                    ByVal PERIODO_ID As Integer,  _
                    ByVal FECHA_ASISTENCIA As Date,  _
                    ByVal HORA_ENTRADA As Date,  _
                    ByVal HORA_SALIDA As Date,  _
                    ByVal HORAS_TRABAJADAS As Date,  _
                    ByVal HORAS_EXTRAS_DIURNAS As Date,  _
                    ByVal HORAS_EXTRAS_NOCTURNAS As Date,  _
                    ByVal MEDIO_DIA As Boolean,  _
                    ByVal HORAS_ATRASOS As Date,  _
                    ByVal HORAS_EXTRAS_DIURNAS_AUTORIZADAS As Date,  _
                    ByVal HORAS_EXTRAS_NOCTURNAS_AUTORIZADAS As Date,  _
                    ByVal MEDIO_DIA_AUTORIZADO As Boolean,  _
                    ByVal TIPO_EVENTO_ADMIN_ID As Integer,  _
                    ByVal HORAS_ATRASOS_AUTORIZADOS As Date,  _
                    ByVal ANO_REAL As Short,  _
                    ByVal MES_REAL As Byte,  _
                    ByVal OBSERVACIONES As String,  _
                    ByVal FECHA_MODIFICACION As Date,  _
                    ByVal USUARIO As String) As RH_PER_CONTROL_ASISTENCIARow
            Dim rowRH_PER_CONTROL_ASISTENCIARow As RH_PER_CONTROL_ASISTENCIARow = CType(Me.NewRow,RH_PER_CONTROL_ASISTENCIARow)
            Dim columnValuesArray() As Object = New Object() {Nothing, EMPLEADO_ID, PERIODO_ID, FECHA_ASISTENCIA, HORA_ENTRADA, HORA_SALIDA, HORAS_TRABAJADAS, HORAS_EXTRAS_DIURNAS, HORAS_EXTRAS_NOCTURNAS, MEDIO_DIA, HORAS_ATRASOS, HORAS_EXTRAS_DIURNAS_AUTORIZADAS, HORAS_EXTRAS_NOCTURNAS_AUTORIZADAS, MEDIO_DIA_AUTORIZADO, TIPO_EVENTO_ADMIN_ID, HORAS_ATRASOS_AUTORIZADOS, ANO_REAL, MES_REAL, OBSERVACIONES, FECHA_MODIFICACION, USUARIO}
            rowRH_PER_CONTROL_ASISTENCIARow.ItemArray = columnValuesArray
            Me.Rows.Add(rowRH_PER_CONTROL_ASISTENCIARow)
            Return rowRH_PER_CONTROL_ASISTENCIARow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function FindByASISTENCIA_ID(ByVal ASISTENCIA_ID As Integer) As RH_PER_CONTROL_ASISTENCIARow
            Return CType(Me.Rows.Find(New Object() {ASISTENCIA_ID}),RH_PER_CONTROL_ASISTENCIARow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As RH_PER_CONTROL_ASISTENCIADataTable = CType(MyBase.Clone,RH_PER_CONTROL_ASISTENCIADataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New RH_PER_CONTROL_ASISTENCIADataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnASISTENCIA_ID = MyBase.Columns("ASISTENCIA_ID")
            Me.columnEMPLEADO_ID = MyBase.Columns("EMPLEADO_ID")
            Me.columnPERIODO_ID = MyBase.Columns("PERIODO_ID")
            Me.columnFECHA_ASISTENCIA = MyBase.Columns("FECHA_ASISTENCIA")
            Me.columnHORA_ENTRADA = MyBase.Columns("HORA_ENTRADA")
            Me.columnHORA_SALIDA = MyBase.Columns("HORA_SALIDA")
            Me.columnHORAS_TRABAJADAS = MyBase.Columns("HORAS_TRABAJADAS")
            Me.columnHORAS_EXTRAS_DIURNAS = MyBase.Columns("HORAS_EXTRAS_DIURNAS")
            Me.columnHORAS_EXTRAS_NOCTURNAS = MyBase.Columns("HORAS_EXTRAS_NOCTURNAS")
            Me.columnMEDIO_DIA = MyBase.Columns("MEDIO_DIA")
            Me.columnHORAS_ATRASOS = MyBase.Columns("HORAS_ATRASOS")
            Me.columnHORAS_EXTRAS_DIURNAS_AUTORIZADAS = MyBase.Columns("HORAS_EXTRAS_DIURNAS_AUTORIZADAS")
            Me.columnHORAS_EXTRAS_NOCTURNAS_AUTORIZADAS = MyBase.Columns("HORAS_EXTRAS_NOCTURNAS_AUTORIZADAS")
            Me.columnMEDIO_DIA_AUTORIZADO = MyBase.Columns("MEDIO_DIA_AUTORIZADO")
            Me.columnTIPO_EVENTO_ADMIN_ID = MyBase.Columns("TIPO_EVENTO_ADMIN_ID")
            Me.columnHORAS_ATRASOS_AUTORIZADOS = MyBase.Columns("HORAS_ATRASOS_AUTORIZADOS")
            Me.columnANO_REAL = MyBase.Columns("ANO_REAL")
            Me.columnMES_REAL = MyBase.Columns("MES_REAL")
            Me.columnOBSERVACIONES = MyBase.Columns("OBSERVACIONES")
            Me.columnFECHA_MODIFICACION = MyBase.Columns("FECHA_MODIFICACION")
            Me.columnUSUARIO = MyBase.Columns("USUARIO")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnASISTENCIA_ID = New Global.System.Data.DataColumn("ASISTENCIA_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnASISTENCIA_ID)
            Me.columnEMPLEADO_ID = New Global.System.Data.DataColumn("EMPLEADO_ID", GetType(Short), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEMPLEADO_ID)
            Me.columnPERIODO_ID = New Global.System.Data.DataColumn("PERIODO_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPERIODO_ID)
            Me.columnFECHA_ASISTENCIA = New Global.System.Data.DataColumn("FECHA_ASISTENCIA", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFECHA_ASISTENCIA)
            Me.columnHORA_ENTRADA = New Global.System.Data.DataColumn("HORA_ENTRADA", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORA_ENTRADA)
            Me.columnHORA_SALIDA = New Global.System.Data.DataColumn("HORA_SALIDA", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORA_SALIDA)
            Me.columnHORAS_TRABAJADAS = New Global.System.Data.DataColumn("HORAS_TRABAJADAS", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORAS_TRABAJADAS)
            Me.columnHORAS_EXTRAS_DIURNAS = New Global.System.Data.DataColumn("HORAS_EXTRAS_DIURNAS", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORAS_EXTRAS_DIURNAS)
            Me.columnHORAS_EXTRAS_NOCTURNAS = New Global.System.Data.DataColumn("HORAS_EXTRAS_NOCTURNAS", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORAS_EXTRAS_NOCTURNAS)
            Me.columnMEDIO_DIA = New Global.System.Data.DataColumn("MEDIO_DIA", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMEDIO_DIA)
            Me.columnHORAS_ATRASOS = New Global.System.Data.DataColumn("HORAS_ATRASOS", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORAS_ATRASOS)
            Me.columnHORAS_EXTRAS_DIURNAS_AUTORIZADAS = New Global.System.Data.DataColumn("HORAS_EXTRAS_DIURNAS_AUTORIZADAS", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORAS_EXTRAS_DIURNAS_AUTORIZADAS)
            Me.columnHORAS_EXTRAS_NOCTURNAS_AUTORIZADAS = New Global.System.Data.DataColumn("HORAS_EXTRAS_NOCTURNAS_AUTORIZADAS", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORAS_EXTRAS_NOCTURNAS_AUTORIZADAS)
            Me.columnMEDIO_DIA_AUTORIZADO = New Global.System.Data.DataColumn("MEDIO_DIA_AUTORIZADO", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMEDIO_DIA_AUTORIZADO)
            Me.columnTIPO_EVENTO_ADMIN_ID = New Global.System.Data.DataColumn("TIPO_EVENTO_ADMIN_ID", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTIPO_EVENTO_ADMIN_ID)
            Me.columnHORAS_ATRASOS_AUTORIZADOS = New Global.System.Data.DataColumn("HORAS_ATRASOS_AUTORIZADOS", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORAS_ATRASOS_AUTORIZADOS)
            Me.columnANO_REAL = New Global.System.Data.DataColumn("ANO_REAL", GetType(Short), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnANO_REAL)
            Me.columnMES_REAL = New Global.System.Data.DataColumn("MES_REAL", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMES_REAL)
            Me.columnOBSERVACIONES = New Global.System.Data.DataColumn("OBSERVACIONES", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOBSERVACIONES)
            Me.columnFECHA_MODIFICACION = New Global.System.Data.DataColumn("FECHA_MODIFICACION", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFECHA_MODIFICACION)
            Me.columnUSUARIO = New Global.System.Data.DataColumn("USUARIO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUSUARIO)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("DSControlAsistenciaKey1", New Global.System.Data.DataColumn() {Me.columnASISTENCIA_ID}, true))
            Me.columnASISTENCIA_ID.AutoIncrement = true
            Me.columnASISTENCIA_ID.AllowDBNull = false
            Me.columnASISTENCIA_ID.ReadOnly = true
            Me.columnASISTENCIA_ID.Unique = true
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function NewRH_PER_CONTROL_ASISTENCIARow() As RH_PER_CONTROL_ASISTENCIARow
            Return CType(Me.NewRow,RH_PER_CONTROL_ASISTENCIARow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New RH_PER_CONTROL_ASISTENCIARow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(RH_PER_CONTROL_ASISTENCIARow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.RH_PER_CONTROL_ASISTENCIARowChangedEvent) Is Nothing) Then
                RaiseEvent RH_PER_CONTROL_ASISTENCIARowChanged(Me, New RH_PER_CONTROL_ASISTENCIARowChangeEvent(CType(e.Row,RH_PER_CONTROL_ASISTENCIARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.RH_PER_CONTROL_ASISTENCIARowChangingEvent) Is Nothing) Then
                RaiseEvent RH_PER_CONTROL_ASISTENCIARowChanging(Me, New RH_PER_CONTROL_ASISTENCIARowChangeEvent(CType(e.Row,RH_PER_CONTROL_ASISTENCIARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.RH_PER_CONTROL_ASISTENCIARowDeletedEvent) Is Nothing) Then
                RaiseEvent RH_PER_CONTROL_ASISTENCIARowDeleted(Me, New RH_PER_CONTROL_ASISTENCIARowChangeEvent(CType(e.Row,RH_PER_CONTROL_ASISTENCIARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.RH_PER_CONTROL_ASISTENCIARowDeletingEvent) Is Nothing) Then
                RaiseEvent RH_PER_CONTROL_ASISTENCIARowDeleting(Me, New RH_PER_CONTROL_ASISTENCIARowChangeEvent(CType(e.Row,RH_PER_CONTROL_ASISTENCIARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub RemoveRH_PER_CONTROL_ASISTENCIARow(ByVal row As RH_PER_CONTROL_ASISTENCIARow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As DSControlAsistencia = New DSControlAsistencia()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "RH_PER_CONTROL_ASISTENCIADataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class RH_PER_CONTROL_ASISTENCIARow
        Inherits Global.System.Data.DataRow
        
        Private tableRH_PER_CONTROL_ASISTENCIA As RH_PER_CONTROL_ASISTENCIADataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableRH_PER_CONTROL_ASISTENCIA = CType(Me.Table,RH_PER_CONTROL_ASISTENCIADataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ASISTENCIA_ID() As Integer
            Get
                Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.ASISTENCIA_IDColumn),Integer)
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.ASISTENCIA_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property EMPLEADO_ID() As Short
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.EMPLEADO_IDColumn),Short)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EMPLEADO_ID' in table 'RH_PER_CONTROL_ASISTENCIA' is DBNull"& _ 
                            ".", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.EMPLEADO_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PERIODO_ID() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.PERIODO_IDColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PERIODO_ID' in table 'RH_PER_CONTROL_ASISTENCIA' is DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.PERIODO_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FECHA_ASISTENCIA() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.FECHA_ASISTENCIAColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FECHA_ASISTENCIA' in table 'RH_PER_CONTROL_ASISTENCIA' is D"& _ 
                            "BNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.FECHA_ASISTENCIAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORA_ENTRADA() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORA_ENTRADAColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HORA_ENTRADA' in table 'RH_PER_CONTROL_ASISTENCIA' is DBNul"& _ 
                            "l.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORA_ENTRADAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORA_SALIDA() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORA_SALIDAColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HORA_SALIDA' in table 'RH_PER_CONTROL_ASISTENCIA' is DBNull"& _ 
                            ".", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORA_SALIDAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORAS_TRABAJADAS() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_TRABAJADASColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HORAS_TRABAJADAS' in table 'RH_PER_CONTROL_ASISTENCIA' is D"& _ 
                            "BNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_TRABAJADASColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORAS_EXTRAS_DIURNAS() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_DIURNASColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HORAS_EXTRAS_DIURNAS' in table 'RH_PER_CONTROL_ASISTENCIA' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_DIURNASColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORAS_EXTRAS_NOCTURNAS() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_NOCTURNASColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HORAS_EXTRAS_NOCTURNAS' in table 'RH_PER_CONTROL_ASISTENCIA"& _ 
                            "' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_NOCTURNASColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MEDIO_DIA() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.MEDIO_DIAColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'MEDIO_DIA' in table 'RH_PER_CONTROL_ASISTENCIA' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.MEDIO_DIAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORAS_ATRASOS() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_ATRASOSColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HORAS_ATRASOS' in table 'RH_PER_CONTROL_ASISTENCIA' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_ATRASOSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORAS_EXTRAS_DIURNAS_AUTORIZADAS() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_DIURNAS_AUTORIZADASColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HORAS_EXTRAS_DIURNAS_AUTORIZADAS' in table 'RH_PER_CONTROL_"& _ 
                            "ASISTENCIA' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_DIURNAS_AUTORIZADASColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORAS_EXTRAS_NOCTURNAS_AUTORIZADAS() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_NOCTURNAS_AUTORIZADASColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HORAS_EXTRAS_NOCTURNAS_AUTORIZADAS' in table 'RH_PER_CONTRO"& _ 
                            "L_ASISTENCIA' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_NOCTURNAS_AUTORIZADASColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MEDIO_DIA_AUTORIZADO() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.MEDIO_DIA_AUTORIZADOColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'MEDIO_DIA_AUTORIZADO' in table 'RH_PER_CONTROL_ASISTENCIA' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.MEDIO_DIA_AUTORIZADOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TIPO_EVENTO_ADMIN_ID() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.TIPO_EVENTO_ADMIN_IDColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TIPO_EVENTO_ADMIN_ID' in table 'RH_PER_CONTROL_ASISTENCIA' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.TIPO_EVENTO_ADMIN_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORAS_ATRASOS_AUTORIZADOS() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_ATRASOS_AUTORIZADOSColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'HORAS_ATRASOS_AUTORIZADOS' in table 'RH_PER_CONTROL_ASISTEN"& _ 
                            "CIA' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_ATRASOS_AUTORIZADOSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ANO_REAL() As Short
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.ANO_REALColumn),Short)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ANO_REAL' in table 'RH_PER_CONTROL_ASISTENCIA' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.ANO_REALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MES_REAL() As Byte
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.MES_REALColumn),Byte)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'MES_REAL' in table 'RH_PER_CONTROL_ASISTENCIA' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.MES_REALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property OBSERVACIONES() As String
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.OBSERVACIONESColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'OBSERVACIONES' in table 'RH_PER_CONTROL_ASISTENCIA' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.OBSERVACIONESColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FECHA_MODIFICACION() As Date
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.FECHA_MODIFICACIONColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FECHA_MODIFICACION' in table 'RH_PER_CONTROL_ASISTENCIA' is"& _ 
                            " DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.FECHA_MODIFICACIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property USUARIO() As String
            Get
                Try 
                    Return CType(Me(Me.tableRH_PER_CONTROL_ASISTENCIA.USUARIOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'USUARIO' in table 'RH_PER_CONTROL_ASISTENCIA' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableRH_PER_CONTROL_ASISTENCIA.USUARIOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsEMPLEADO_IDNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.EMPLEADO_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetEMPLEADO_IDNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.EMPLEADO_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPERIODO_IDNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.PERIODO_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPERIODO_IDNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.PERIODO_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsFECHA_ASISTENCIANull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.FECHA_ASISTENCIAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetFECHA_ASISTENCIANull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.FECHA_ASISTENCIAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHORA_ENTRADANull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.HORA_ENTRADAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHORA_ENTRADANull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORA_ENTRADAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHORA_SALIDANull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.HORA_SALIDAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHORA_SALIDANull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORA_SALIDAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHORAS_TRABAJADASNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_TRABAJADASColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHORAS_TRABAJADASNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_TRABAJADASColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHORAS_EXTRAS_DIURNASNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_DIURNASColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHORAS_EXTRAS_DIURNASNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_DIURNASColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHORAS_EXTRAS_NOCTURNASNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_NOCTURNASColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHORAS_EXTRAS_NOCTURNASNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_NOCTURNASColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsMEDIO_DIANull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.MEDIO_DIAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetMEDIO_DIANull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.MEDIO_DIAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHORAS_ATRASOSNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_ATRASOSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHORAS_ATRASOSNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_ATRASOSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHORAS_EXTRAS_DIURNAS_AUTORIZADASNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_DIURNAS_AUTORIZADASColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHORAS_EXTRAS_DIURNAS_AUTORIZADASNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_DIURNAS_AUTORIZADASColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHORAS_EXTRAS_NOCTURNAS_AUTORIZADASNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_NOCTURNAS_AUTORIZADASColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHORAS_EXTRAS_NOCTURNAS_AUTORIZADASNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_EXTRAS_NOCTURNAS_AUTORIZADASColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsMEDIO_DIA_AUTORIZADONull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.MEDIO_DIA_AUTORIZADOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetMEDIO_DIA_AUTORIZADONull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.MEDIO_DIA_AUTORIZADOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTIPO_EVENTO_ADMIN_IDNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.TIPO_EVENTO_ADMIN_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTIPO_EVENTO_ADMIN_IDNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.TIPO_EVENTO_ADMIN_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHORAS_ATRASOS_AUTORIZADOSNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_ATRASOS_AUTORIZADOSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHORAS_ATRASOS_AUTORIZADOSNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.HORAS_ATRASOS_AUTORIZADOSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsANO_REALNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.ANO_REALColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetANO_REALNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.ANO_REALColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsMES_REALNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.MES_REALColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetMES_REALNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.MES_REALColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsOBSERVACIONESNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.OBSERVACIONESColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetOBSERVACIONESNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.OBSERVACIONESColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsFECHA_MODIFICACIONNull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.FECHA_MODIFICACIONColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetFECHA_MODIFICACIONNull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.FECHA_MODIFICACIONColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsUSUARIONull() As Boolean
            Return Me.IsNull(Me.tableRH_PER_CONTROL_ASISTENCIA.USUARIOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetUSUARIONull()
            Me(Me.tableRH_PER_CONTROL_ASISTENCIA.USUARIOColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class RH_PER_CONTROL_ASISTENCIARowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As RH_PER_CONTROL_ASISTENCIARow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As RH_PER_CONTROL_ASISTENCIARow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As RH_PER_CONTROL_ASISTENCIARow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
