'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DsMaestroEmpleadosDIPRES"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DsMaestroEmpleadosDIPRES
    Inherits Global.System.Data.DataSet
    
    Private tableVW_MAESTRO_EMPLEADO_DIPRES As VW_MAESTRO_EMPLEADO_DIPRESDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("VW_MAESTRO_EMPLEADO_DIPRES")) Is Nothing) Then
                MyBase.Tables.Add(New VW_MAESTRO_EMPLEADO_DIPRESDataTable(ds.Tables("VW_MAESTRO_EMPLEADO_DIPRES")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property VW_MAESTRO_EMPLEADO_DIPRES() As VW_MAESTRO_EMPLEADO_DIPRESDataTable
        Get
            Return Me.tableVW_MAESTRO_EMPLEADO_DIPRES
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DsMaestroEmpleadosDIPRES = CType(MyBase.Clone,DsMaestroEmpleadosDIPRES)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("VW_MAESTRO_EMPLEADO_DIPRES")) Is Nothing) Then
                MyBase.Tables.Add(New VW_MAESTRO_EMPLEADO_DIPRESDataTable(ds.Tables("VW_MAESTRO_EMPLEADO_DIPRES")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableVW_MAESTRO_EMPLEADO_DIPRES = CType(MyBase.Tables("VW_MAESTRO_EMPLEADO_DIPRES"),VW_MAESTRO_EMPLEADO_DIPRESDataTable)
        If (initTable = true) Then
            If (Not (Me.tableVW_MAESTRO_EMPLEADO_DIPRES) Is Nothing) Then
                Me.tableVW_MAESTRO_EMPLEADO_DIPRES.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "DsMaestroEmpleadosDIPRES"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DsMaestroEmpleadosDIPRES.xsd"
        Me.Locale = New Global.System.Globalization.CultureInfo("es-CL")
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableVW_MAESTRO_EMPLEADO_DIPRES = New VW_MAESTRO_EMPLEADO_DIPRESDataTable()
        MyBase.Tables.Add(Me.tableVW_MAESTRO_EMPLEADO_DIPRES)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializeVW_MAESTRO_EMPLEADO_DIPRES() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DsMaestroEmpleadosDIPRES = New DsMaestroEmpleadosDIPRES()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub VW_MAESTRO_EMPLEADO_DIPRESRowChangeEventHandler(ByVal sender As Object, ByVal e As VW_MAESTRO_EMPLEADO_DIPRESRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class VW_MAESTRO_EMPLEADO_DIPRESDataTable
        Inherits Global.System.Data.TypedTableBase(Of VW_MAESTRO_EMPLEADO_DIPRESRow)
        
        Private columnESTADO_REGISTRO As Global.System.Data.DataColumn
        
        Private columnDESCRIPCION_PERIODO As Global.System.Data.DataColumn
        
        Private columnORGANIZACION_ID As Global.System.Data.DataColumn
        
        Private columnESTADO_EMPLEADO As Global.System.Data.DataColumn
        
        Private columnEMPLEADO_ID As Global.System.Data.DataColumn
        
        Private columnRUT As Global.System.Data.DataColumn
        
        Private columnDV As Global.System.Data.DataColumn
        
        Private columnNOMBRE_EMPLEADO As Global.System.Data.DataColumn
        
        Private columnCALIDAD_JURIDICA As Global.System.Data.DataColumn
        
        Private columnESTAMENTO_DIPRES As Global.System.Data.DataColumn
        
        Private columnESTAMENTO_RRHH As Global.System.Data.DataColumn
        
        Private columnCLASIFICACION_EMPLEADO As Global.System.Data.DataColumn
        
        Private columnGRADO As Global.System.Data.DataColumn
        
        Private columnFECHA_ING_INSTITUCION As Global.System.Data.DataColumn
        
        Private columnSEXO As Global.System.Data.DataColumn
        
        Private columnFECHA_RETIRO As Global.System.Data.DataColumn
        
        Private columnMOTIVO_RETIRO As Global.System.Data.DataColumn
        
        Private columnRETIRO_APLICA_DIPRES As Global.System.Data.DataColumn
        
        Private columnEDAD As Global.System.Data.DataColumn
        
        Private columnSISTEMA_PREVISIONAL As Global.System.Data.DataColumn
        
        Private columnSISTEMA_PREVISIONAL_SALUD As Global.System.Data.DataColumn
        
        Private columnCANTIDAD As Global.System.Data.DataColumn
        
        Private columnTIPO_MOVIMIENTO As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "VW_MAESTRO_EMPLEADO_DIPRES"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ESTADO_REGISTROColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnESTADO_REGISTRO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DESCRIPCION_PERIODOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDESCRIPCION_PERIODO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ORGANIZACION_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORGANIZACION_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ESTADO_EMPLEADOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnESTADO_EMPLEADO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property EMPLEADO_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEMPLEADO_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property RUTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRUT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DVColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDV
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property NOMBRE_EMPLEADOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNOMBRE_EMPLEADO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CALIDAD_JURIDICAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCALIDAD_JURIDICA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ESTAMENTO_DIPRESColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnESTAMENTO_DIPRES
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ESTAMENTO_RRHHColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnESTAMENTO_RRHH
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CLASIFICACION_EMPLEADOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCLASIFICACION_EMPLEADO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property GRADOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGRADO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FECHA_ING_INSTITUCIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFECHA_ING_INSTITUCION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SEXOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSEXO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property FECHA_RETIROColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnFECHA_RETIRO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MOTIVO_RETIROColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMOTIVO_RETIRO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property RETIRO_APLICA_DIPRESColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRETIRO_APLICA_DIPRES
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property EDADColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEDAD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SISTEMA_PREVISIONALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSISTEMA_PREVISIONAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SISTEMA_PREVISIONAL_SALUDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSISTEMA_PREVISIONAL_SALUD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CANTIDADColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCANTIDAD
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TIPO_MOVIMIENTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTIPO_MOVIMIENTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As VW_MAESTRO_EMPLEADO_DIPRESRow
            Get
                Return CType(Me.Rows(index),VW_MAESTRO_EMPLEADO_DIPRESRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event VW_MAESTRO_EMPLEADO_DIPRESRowChanging As VW_MAESTRO_EMPLEADO_DIPRESRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event VW_MAESTRO_EMPLEADO_DIPRESRowChanged As VW_MAESTRO_EMPLEADO_DIPRESRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event VW_MAESTRO_EMPLEADO_DIPRESRowDeleting As VW_MAESTRO_EMPLEADO_DIPRESRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event VW_MAESTRO_EMPLEADO_DIPRESRowDeleted As VW_MAESTRO_EMPLEADO_DIPRESRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub AddVW_MAESTRO_EMPLEADO_DIPRESRow(ByVal row As VW_MAESTRO_EMPLEADO_DIPRESRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function AddVW_MAESTRO_EMPLEADO_DIPRESRow( _
                    ByVal ESTADO_REGISTRO As String,  _
                    ByVal DESCRIPCION_PERIODO As String,  _
                    ByVal ORGANIZACION_ID As Byte,  _
                    ByVal ESTADO_EMPLEADO As String,  _
                    ByVal EMPLEADO_ID As Short,  _
                    ByVal RUT As Integer,  _
                    ByVal DV As String,  _
                    ByVal NOMBRE_EMPLEADO As String,  _
                    ByVal CALIDAD_JURIDICA As String,  _
                    ByVal ESTAMENTO_DIPRES As String,  _
                    ByVal ESTAMENTO_RRHH As String,  _
                    ByVal CLASIFICACION_EMPLEADO As String,  _
                    ByVal GRADO As String,  _
                    ByVal FECHA_ING_INSTITUCION As Date,  _
                    ByVal SEXO As String,  _
                    ByVal FECHA_RETIRO As Date,  _
                    ByVal MOTIVO_RETIRO As String,  _
                    ByVal RETIRO_APLICA_DIPRES As Boolean,  _
                    ByVal EDAD As Integer,  _
                    ByVal SISTEMA_PREVISIONAL As String,  _
                    ByVal SISTEMA_PREVISIONAL_SALUD As String,  _
                    ByVal CANTIDAD As Integer,  _
                    ByVal TIPO_MOVIMIENTO As String) As VW_MAESTRO_EMPLEADO_DIPRESRow
            Dim rowVW_MAESTRO_EMPLEADO_DIPRESRow As VW_MAESTRO_EMPLEADO_DIPRESRow = CType(Me.NewRow,VW_MAESTRO_EMPLEADO_DIPRESRow)
            Dim columnValuesArray() As Object = New Object() {ESTADO_REGISTRO, DESCRIPCION_PERIODO, ORGANIZACION_ID, ESTADO_EMPLEADO, EMPLEADO_ID, RUT, DV, NOMBRE_EMPLEADO, CALIDAD_JURIDICA, ESTAMENTO_DIPRES, ESTAMENTO_RRHH, CLASIFICACION_EMPLEADO, GRADO, FECHA_ING_INSTITUCION, SEXO, FECHA_RETIRO, MOTIVO_RETIRO, RETIRO_APLICA_DIPRES, EDAD, SISTEMA_PREVISIONAL, SISTEMA_PREVISIONAL_SALUD, CANTIDAD, TIPO_MOVIMIENTO}
            rowVW_MAESTRO_EMPLEADO_DIPRESRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowVW_MAESTRO_EMPLEADO_DIPRESRow)
            Return rowVW_MAESTRO_EMPLEADO_DIPRESRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As VW_MAESTRO_EMPLEADO_DIPRESDataTable = CType(MyBase.Clone,VW_MAESTRO_EMPLEADO_DIPRESDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New VW_MAESTRO_EMPLEADO_DIPRESDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnESTADO_REGISTRO = MyBase.Columns("ESTADO_REGISTRO")
            Me.columnDESCRIPCION_PERIODO = MyBase.Columns("DESCRIPCION_PERIODO")
            Me.columnORGANIZACION_ID = MyBase.Columns("ORGANIZACION_ID")
            Me.columnESTADO_EMPLEADO = MyBase.Columns("ESTADO_EMPLEADO")
            Me.columnEMPLEADO_ID = MyBase.Columns("EMPLEADO_ID")
            Me.columnRUT = MyBase.Columns("RUT")
            Me.columnDV = MyBase.Columns("DV")
            Me.columnNOMBRE_EMPLEADO = MyBase.Columns("NOMBRE_EMPLEADO")
            Me.columnCALIDAD_JURIDICA = MyBase.Columns("CALIDAD_JURIDICA")
            Me.columnESTAMENTO_DIPRES = MyBase.Columns("ESTAMENTO_DIPRES")
            Me.columnESTAMENTO_RRHH = MyBase.Columns("ESTAMENTO_RRHH")
            Me.columnCLASIFICACION_EMPLEADO = MyBase.Columns("CLASIFICACION_EMPLEADO")
            Me.columnGRADO = MyBase.Columns("GRADO")
            Me.columnFECHA_ING_INSTITUCION = MyBase.Columns("FECHA_ING_INSTITUCION")
            Me.columnSEXO = MyBase.Columns("SEXO")
            Me.columnFECHA_RETIRO = MyBase.Columns("FECHA_RETIRO")
            Me.columnMOTIVO_RETIRO = MyBase.Columns("MOTIVO_RETIRO")
            Me.columnRETIRO_APLICA_DIPRES = MyBase.Columns("RETIRO_APLICA_DIPRES")
            Me.columnEDAD = MyBase.Columns("EDAD")
            Me.columnSISTEMA_PREVISIONAL = MyBase.Columns("SISTEMA_PREVISIONAL")
            Me.columnSISTEMA_PREVISIONAL_SALUD = MyBase.Columns("SISTEMA_PREVISIONAL_SALUD")
            Me.columnCANTIDAD = MyBase.Columns("CANTIDAD")
            Me.columnTIPO_MOVIMIENTO = MyBase.Columns("TIPO_MOVIMIENTO")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnESTADO_REGISTRO = New Global.System.Data.DataColumn("ESTADO_REGISTRO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnESTADO_REGISTRO)
            Me.columnDESCRIPCION_PERIODO = New Global.System.Data.DataColumn("DESCRIPCION_PERIODO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDESCRIPCION_PERIODO)
            Me.columnORGANIZACION_ID = New Global.System.Data.DataColumn("ORGANIZACION_ID", GetType(Byte), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORGANIZACION_ID)
            Me.columnESTADO_EMPLEADO = New Global.System.Data.DataColumn("ESTADO_EMPLEADO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnESTADO_EMPLEADO)
            Me.columnEMPLEADO_ID = New Global.System.Data.DataColumn("EMPLEADO_ID", GetType(Short), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEMPLEADO_ID)
            Me.columnRUT = New Global.System.Data.DataColumn("RUT", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRUT)
            Me.columnDV = New Global.System.Data.DataColumn("DV", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDV)
            Me.columnNOMBRE_EMPLEADO = New Global.System.Data.DataColumn("NOMBRE_EMPLEADO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNOMBRE_EMPLEADO)
            Me.columnCALIDAD_JURIDICA = New Global.System.Data.DataColumn("CALIDAD_JURIDICA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCALIDAD_JURIDICA)
            Me.columnESTAMENTO_DIPRES = New Global.System.Data.DataColumn("ESTAMENTO_DIPRES", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnESTAMENTO_DIPRES)
            Me.columnESTAMENTO_RRHH = New Global.System.Data.DataColumn("ESTAMENTO_RRHH", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnESTAMENTO_RRHH)
            Me.columnCLASIFICACION_EMPLEADO = New Global.System.Data.DataColumn("CLASIFICACION_EMPLEADO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCLASIFICACION_EMPLEADO)
            Me.columnGRADO = New Global.System.Data.DataColumn("GRADO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGRADO)
            Me.columnFECHA_ING_INSTITUCION = New Global.System.Data.DataColumn("FECHA_ING_INSTITUCION", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFECHA_ING_INSTITUCION)
            Me.columnSEXO = New Global.System.Data.DataColumn("SEXO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSEXO)
            Me.columnFECHA_RETIRO = New Global.System.Data.DataColumn("FECHA_RETIRO", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnFECHA_RETIRO)
            Me.columnMOTIVO_RETIRO = New Global.System.Data.DataColumn("MOTIVO_RETIRO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMOTIVO_RETIRO)
            Me.columnRETIRO_APLICA_DIPRES = New Global.System.Data.DataColumn("RETIRO_APLICA_DIPRES", GetType(Boolean), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRETIRO_APLICA_DIPRES)
            Me.columnEDAD = New Global.System.Data.DataColumn("EDAD", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEDAD)
            Me.columnSISTEMA_PREVISIONAL = New Global.System.Data.DataColumn("SISTEMA_PREVISIONAL", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSISTEMA_PREVISIONAL)
            Me.columnSISTEMA_PREVISIONAL_SALUD = New Global.System.Data.DataColumn("SISTEMA_PREVISIONAL_SALUD", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSISTEMA_PREVISIONAL_SALUD)
            Me.columnCANTIDAD = New Global.System.Data.DataColumn("CANTIDAD", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCANTIDAD)
            Me.columnTIPO_MOVIMIENTO = New Global.System.Data.DataColumn("TIPO_MOVIMIENTO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTIPO_MOVIMIENTO)
            Me.columnORGANIZACION_ID.AllowDBNull = false
            Me.columnESTADO_EMPLEADO.AllowDBNull = false
            Me.columnEMPLEADO_ID.AllowDBNull = false
            Me.columnRUT.AllowDBNull = false
            Me.columnDV.AllowDBNull = false
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function NewVW_MAESTRO_EMPLEADO_DIPRESRow() As VW_MAESTRO_EMPLEADO_DIPRESRow
            Return CType(Me.NewRow,VW_MAESTRO_EMPLEADO_DIPRESRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New VW_MAESTRO_EMPLEADO_DIPRESRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(VW_MAESTRO_EMPLEADO_DIPRESRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.VW_MAESTRO_EMPLEADO_DIPRESRowChangedEvent) Is Nothing) Then
                RaiseEvent VW_MAESTRO_EMPLEADO_DIPRESRowChanged(Me, New VW_MAESTRO_EMPLEADO_DIPRESRowChangeEvent(CType(e.Row,VW_MAESTRO_EMPLEADO_DIPRESRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.VW_MAESTRO_EMPLEADO_DIPRESRowChangingEvent) Is Nothing) Then
                RaiseEvent VW_MAESTRO_EMPLEADO_DIPRESRowChanging(Me, New VW_MAESTRO_EMPLEADO_DIPRESRowChangeEvent(CType(e.Row,VW_MAESTRO_EMPLEADO_DIPRESRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.VW_MAESTRO_EMPLEADO_DIPRESRowDeletedEvent) Is Nothing) Then
                RaiseEvent VW_MAESTRO_EMPLEADO_DIPRESRowDeleted(Me, New VW_MAESTRO_EMPLEADO_DIPRESRowChangeEvent(CType(e.Row,VW_MAESTRO_EMPLEADO_DIPRESRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.VW_MAESTRO_EMPLEADO_DIPRESRowDeletingEvent) Is Nothing) Then
                RaiseEvent VW_MAESTRO_EMPLEADO_DIPRESRowDeleting(Me, New VW_MAESTRO_EMPLEADO_DIPRESRowChangeEvent(CType(e.Row,VW_MAESTRO_EMPLEADO_DIPRESRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub RemoveVW_MAESTRO_EMPLEADO_DIPRESRow(ByVal row As VW_MAESTRO_EMPLEADO_DIPRESRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As DsMaestroEmpleadosDIPRES = New DsMaestroEmpleadosDIPRES()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "VW_MAESTRO_EMPLEADO_DIPRESDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class VW_MAESTRO_EMPLEADO_DIPRESRow
        Inherits Global.System.Data.DataRow
        
        Private tableVW_MAESTRO_EMPLEADO_DIPRES As VW_MAESTRO_EMPLEADO_DIPRESDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableVW_MAESTRO_EMPLEADO_DIPRES = CType(Me.Table,VW_MAESTRO_EMPLEADO_DIPRESDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ESTADO_REGISTRO() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTADO_REGISTROColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ESTADO_REGISTRO' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is D"& _ 
                            "BNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTADO_REGISTROColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DESCRIPCION_PERIODO() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.DESCRIPCION_PERIODOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DESCRIPCION_PERIODO' in table 'VW_MAESTRO_EMPLEADO_DIPRES' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.DESCRIPCION_PERIODOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ORGANIZACION_ID() As Byte
            Get
                Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ORGANIZACION_IDColumn),Byte)
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ORGANIZACION_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ESTADO_EMPLEADO() As String
            Get
                Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTADO_EMPLEADOColumn),String)
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTADO_EMPLEADOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property EMPLEADO_ID() As Short
            Get
                Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.EMPLEADO_IDColumn),Short)
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.EMPLEADO_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property RUT() As Integer
            Get
                Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.RUTColumn),Integer)
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.RUTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DV() As String
            Get
                Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.DVColumn),String)
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.DVColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property NOMBRE_EMPLEADO() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.NOMBRE_EMPLEADOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'NOMBRE_EMPLEADO' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is D"& _ 
                            "BNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.NOMBRE_EMPLEADOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CALIDAD_JURIDICA() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CALIDAD_JURIDICAColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CALIDAD_JURIDICA' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is "& _ 
                            "DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CALIDAD_JURIDICAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ESTAMENTO_DIPRES() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTAMENTO_DIPRESColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ESTAMENTO_DIPRES' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is "& _ 
                            "DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTAMENTO_DIPRESColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ESTAMENTO_RRHH() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTAMENTO_RRHHColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ESTAMENTO_RRHH' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is DB"& _ 
                            "Null.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTAMENTO_RRHHColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CLASIFICACION_EMPLEADO() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CLASIFICACION_EMPLEADOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CLASIFICACION_EMPLEADO' in table 'VW_MAESTRO_EMPLEADO_DIPRE"& _ 
                            "S' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CLASIFICACION_EMPLEADOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property GRADO() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.GRADOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'GRADO' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.GRADOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FECHA_ING_INSTITUCION() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.FECHA_ING_INSTITUCIONColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FECHA_ING_INSTITUCION' in table 'VW_MAESTRO_EMPLEADO_DIPRES"& _ 
                            "' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.FECHA_ING_INSTITUCIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SEXO() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SEXOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SEXO' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SEXOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property FECHA_RETIRO() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.FECHA_RETIROColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'FECHA_RETIRO' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.FECHA_RETIROColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MOTIVO_RETIRO() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.MOTIVO_RETIROColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'MOTIVO_RETIRO' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is DBN"& _ 
                            "ull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.MOTIVO_RETIROColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property RETIRO_APLICA_DIPRES() As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.RETIRO_APLICA_DIPRESColumn),Boolean)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'RETIRO_APLICA_DIPRES' in table 'VW_MAESTRO_EMPLEADO_DIPRES'"& _ 
                            " is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.RETIRO_APLICA_DIPRESColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property EDAD() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.EDADColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EDAD' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.EDADColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SISTEMA_PREVISIONAL() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SISTEMA_PREVISIONALColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SISTEMA_PREVISIONAL' in table 'VW_MAESTRO_EMPLEADO_DIPRES' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SISTEMA_PREVISIONALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SISTEMA_PREVISIONAL_SALUD() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SISTEMA_PREVISIONAL_SALUDColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SISTEMA_PREVISIONAL_SALUD' in table 'VW_MAESTRO_EMPLEADO_DI"& _ 
                            "PRES' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SISTEMA_PREVISIONAL_SALUDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CANTIDAD() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CANTIDADColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CANTIDAD' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CANTIDADColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TIPO_MOVIMIENTO() As String
            Get
                Try 
                    Return CType(Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.TIPO_MOVIMIENTOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TIPO_MOVIMIENTO' in table 'VW_MAESTRO_EMPLEADO_DIPRES' is D"& _ 
                            "BNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.TIPO_MOVIMIENTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsESTADO_REGISTRONull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTADO_REGISTROColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetESTADO_REGISTRONull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTADO_REGISTROColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDESCRIPCION_PERIODONull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.DESCRIPCION_PERIODOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDESCRIPCION_PERIODONull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.DESCRIPCION_PERIODOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsNOMBRE_EMPLEADONull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.NOMBRE_EMPLEADOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetNOMBRE_EMPLEADONull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.NOMBRE_EMPLEADOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCALIDAD_JURIDICANull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CALIDAD_JURIDICAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCALIDAD_JURIDICANull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CALIDAD_JURIDICAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsESTAMENTO_DIPRESNull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTAMENTO_DIPRESColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetESTAMENTO_DIPRESNull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTAMENTO_DIPRESColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsESTAMENTO_RRHHNull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTAMENTO_RRHHColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetESTAMENTO_RRHHNull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.ESTAMENTO_RRHHColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCLASIFICACION_EMPLEADONull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CLASIFICACION_EMPLEADOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCLASIFICACION_EMPLEADONull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CLASIFICACION_EMPLEADOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsGRADONull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.GRADOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetGRADONull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.GRADOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsFECHA_ING_INSTITUCIONNull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.FECHA_ING_INSTITUCIONColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetFECHA_ING_INSTITUCIONNull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.FECHA_ING_INSTITUCIONColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSEXONull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SEXOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSEXONull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SEXOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsFECHA_RETIRONull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.FECHA_RETIROColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetFECHA_RETIRONull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.FECHA_RETIROColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsMOTIVO_RETIRONull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.MOTIVO_RETIROColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetMOTIVO_RETIRONull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.MOTIVO_RETIROColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsRETIRO_APLICA_DIPRESNull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.RETIRO_APLICA_DIPRESColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetRETIRO_APLICA_DIPRESNull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.RETIRO_APLICA_DIPRESColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsEDADNull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.EDADColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetEDADNull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.EDADColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSISTEMA_PREVISIONALNull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SISTEMA_PREVISIONALColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSISTEMA_PREVISIONALNull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SISTEMA_PREVISIONALColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSISTEMA_PREVISIONAL_SALUDNull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SISTEMA_PREVISIONAL_SALUDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSISTEMA_PREVISIONAL_SALUDNull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.SISTEMA_PREVISIONAL_SALUDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCANTIDADNull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CANTIDADColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCANTIDADNull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.CANTIDADColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTIPO_MOVIMIENTONull() As Boolean
            Return Me.IsNull(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.TIPO_MOVIMIENTOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTIPO_MOVIMIENTONull()
            Me(Me.tableVW_MAESTRO_EMPLEADO_DIPRES.TIPO_MOVIMIENTOColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class VW_MAESTRO_EMPLEADO_DIPRESRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As VW_MAESTRO_EMPLEADO_DIPRESRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As VW_MAESTRO_EMPLEADO_DIPRESRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As VW_MAESTRO_EMPLEADO_DIPRESRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
